# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: graphql-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data/

  bookstore-services:
    container_name: graphql-bookstore-application
    build: .
    ports:
      - "8080:8081"
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookstore
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      SPRING_GRAPHQL_GRAPHIQL_ENABLED: true
      SPRING_GRAPHQL_GRAPHIQL_PATH: /graphiql
    depends_on:
      - db
volumes:
  db-data: